### ISSUE TITLE
Vulkan-On-12 (aka Dozen) might be incompatible with some applications, should not be default

### ISSUE THREAD

**Issue by madame-rachelle** [microsoft/DirectX-Specs#160]
Recently there seems to be a push for vulkan_dzn.dll loading in place of a native GPU vendor's driver.

Not all applications are compatible with this. Example: GZDoom -> https://forum.zdoom.org/viewtopic.php?t=78470

The long and short of it is: If a GPU vendor (especially one that typically provides good support on Windows, such as NVidia) provides their own Vulkan driver, then the Mesa/Dozen implementation should not try to insert itself as the first available Vulkan device, as this can lead to problems down the road, even if the immediate incompatibilities (of which there are a few) are addressed.

**Comment by jenatali** [comment]
1. There's no real reason for people to have the CL/GL/VK compatibility pack installed on x64 systems. It's intended for ARM devices with no native drivers. Simply uninstall it.
2. It's not intended to be a default. See https://github.com/KhronosGroup/Vulkan-Loader/pull/1342. If you're seeing it show up as a default, update your loader by installing a new Vulkan runtime.

**Comment by Squall-Leonhart** [comment]
Thats some short sighted thinking there, Jenatali.  Some of these users are developers that are intending to test their software against Dozen, or the OpenGL aspect of the compatibility pack in order to eradicate bugs that might occur, its even useful as a reference device.

there do exist some cases of x86 DX12 drivers that have worse opengl/vulkan compliance than that which the pack offers - Intel Gen 7 through 11 for instance has misbehaviors in its SPIRV support which causes strange misbehaviors in RDP Emulation for example.

**Comment by jenatali** [comment]
That's fair. In general I do not expect the compat pack to be problematic on x86 or x64. I can understand that there are some compat issues from the sudden arrival of a Vulkan driver where there was not one before.

My hope is that if an *app* wants to use a mapping driver always, they are free to bundle that layer with their app, since they are just MIT open source software. If an x64 driver wants to use a mapping layer as their driver, then things get a bit more complicated. But at this time the only such driver is Basic Render / WARP, which is a very niche scenario.
