### ISSUE TITLE
Enhancd Barrier spec:  Simultaneous access clearer wording

### ISSUE THREAD

**Issue by GertyP** [microsoft/DirectX-Specs#168]
I find the enhanced barrier specs a little less clear on the subject of simultaneously reading and writing a texture/buffer than it could be.

Most of this subject in the spec talks about legacy resource barriers -
1. [Simultaneous Access - But Only Across Queues](https://microsoft.github.io/DirectX-Specs/d3d/D3D12EnhancedBarriers.html#simultaneous-access---but-only-across-queues)
2. [Single-Queue Simultaneous Access](https://microsoft.github.io/DirectX-Specs/d3d/D3D12EnhancedBarriers.html#single-queue-simultaneous-access)
3. [Interop with legacy ResourceBarrier](https://microsoft.github.io/DirectX-Specs/d3d/D3D12EnhancedBarriers.html#interop-with-legacy-resourcebarrier)

If I approach the spec with the question, "What do I need to have a texture both read via an SRV and written via UAV, in either a single dispatch or alternatively with different reads and write from cross-queue dispatches (all with non-overlapping regions)?" then 1. says -
> Buffers and simultaneous-access resources can be written to in one queue while concurrently being read-from one or more OTHER queues

A reader might then think, "OK.  How?  It just says it can be done but doesn't clearly say exactly what's required under the heading that describes this subject.  Also, it explicitly refers to 'Buffers' only; no mention of textures here, so what about them?"

It then goes on to say -
> this pattern is not supported in a single queue because legacy Resource Barrier design prevents subresources from being in both READ and WRITE states at the same time. However, hardware can support same-queue simultaneous-access; Layout is always COMMON and there is no sync or flush needed since the reads are non-dependent.

The meaning of this could easily be interpreted as either, "Using the legacy barriers only, this cannot be done... However, using enhanced barriers, it can if you ensure your resource is in D3D12_BARRIER_LAYOUT_COMMON" or, at a stretch, it could mean, "You cannot do this at all (legacy or enhanced) because of a legacy barrier design, even though hardware could do it".

Also. saying "hardware" can support, is notably conspicuous because it seems intentional that it doesn't say the "enhanced barrier API can support...".

However, saying -
> Layout is always COMMON and there is no sync or flush needed

seems to strongly imply that, for enhanced barriers, transitioning a resource to D3D12_BARRIER_LAYOUT...COMMON will actually allow simultaneous reads and writes ... "But Only Across Queues" (which is the heading we're under and and subject we're talking about), so that leaves the question of "What about same-queue?"

Moving on to 2. -
> The enhanced Barrier API allows concurrent read write operations on the same buffer or simultaneous-access texture in the same command queue.

... Here seems the perfect place to spell out what the enhanced barrier API requires to do this, but it doesn't (explicitly, at least); it goes on to talk about what has previousl been possible and not possible under legacy resource barriers again.

In summary, in order to answer the question, "What do I need to have a texture both read via an SRV and written via UAV, in either a single dispatch or alternatively with different reads that are simultaneous to a cross-queue write dispatch (with non-overlapping regions)?", there's quite a bit of fragented, fluid interleaving of legacy and enhanced barrier notes and unusual wording of partial scenarios that seem to unnecessarily muddy the waters when, after much reading between the lines and pulling different fragments together, I suspect the answer is simply that, under enhanced barriers, same-queue (and cross-queue) reads with a simultaneous write are fine provided the resource is in D3D12_BARRIER_LAYOUT...COMMON (and read regions don't overlap with simultaneous writes) and that more than one writer, even with non-overlapping regions, is not allowed (or undefined) due to potential cache line overlaps.

I think the sections that talk about simultaneous access issues (single and cross-queue) under legacy barriers (1. and 2.) would be clearer if they entirely avoided mixing in fragments of the enhanced barrier API in the same sentence.  Also, adding a 'simultaneous access' heading that's entirely focused on the enhanced barrier API only (covering same-queue and cross-queue scenarios if necessary) and directly answers my example question would improve readability regarding this question.

**Comment by billkris-ms** [comment]
@GertyP, Thank you for the detailed feedback. This is certainly a confusing subject and this spec could probably be more crisp on the subject. Some of the sections describing the state of simultaneous access resources using legacy barriers are an artifact of the spec evolving from a proposal document early in the design. In many cases, those sections existed as an argument for why enhanced barriers were needed. Many of these sections could use updating.

> "Also, it explicitly refers to 'Buffers' only; no mention of textures here, so what about them?"

Actually, it says "Buffers and simultaneous-access resources". However, in most other places in the spec we use to term "simultaneous-access *textures*". So, this should be changed to match that language.

I agree with you that the section "Single-Queue Simultaneous Access" should probably focus on how to use simultaneous access resources with enhanced barriers rather than rehash the problem with legacy barriers.

Regarding concurrent UAV read/write. See [Common Layout](https://microsoft.github.io/DirectX-Specs/d3d/D3D12EnhancedBarriers.html#common-layout). Non-simultaneous access textures using `D3D12_BARRIER_LAYOUT_COMMON` may only be accessed as Copy Source, Copy Dest or Shader Resource (both PS and Non-PS). If you wish to use a texture for UAV read/write concurrent with other read accesses in the same queue, then you must create the texture using `D3D12_RESOURCE_FLAG_ALLOW_SIMULTANEOUS_ACCESS`.

It will likely be a while before I can fully address this feedback. however, I will make at least a few small corrections shortly.
